### PR TITLE
Fix/default values

### LINKED ISSUE #15: Typo in variable and resource name
I suspect you used the word "shiled_advanced" instead of "shield_advanced" everywhere in the code and in the variables.
No typo check at all?

Best,

Luigi

### PR DESCRIPTION
**Pull request by lgallard**
## what
* Change default values to `include_map` and `exclude_map` attributes
* Fix `shiled` typo

## why
* To avoid different types in Terraform conditionals 
* Fix typo in naming resources.

## references
* closes #5 
* closes #15

### CODE REVIEW

**Comment by lgallard** [comment]
@Makeshift @dylanbannon we checked form side  but we are not clear about what permission is needed by `cloudpossebot` in our repo. In fact the forked repo is public https://github.com/binbashar/terraform-aws-firewall-manager 

This the error in your cicd pipeline:

```
remote: Permission to binbashar/terraform-aws-firewall-manager.git denied to cloudpossebot.
fatal: unable to access 'https://github.com/binbashar/terraform-aws-firewall-manager/': The requested URL returned error: 403
```

We introduced several fixes to make the module usable for all fms services, and would like to contribute by sharing those fixes with the community. 

We will be more than pleased if you guide us to merge those changes into your module.

**Comment by lgallard** [comment]
@Makeshift @dylanbannon we did a rebased to fix the conflicts due to your latest changes and hot-fixes, but still having issue with you CI/CD validation. 

We checked form side but we are not clear about what permission is needed by cloudpossebot in our repo. In fact the forked repo is public https://github.com/binbashar/terraform-aws-firewall-manager

Can you help us with this in order to contribute to your module?

Thanks in advance!

cc: @exequielrafaela @diego-ojeda-binbash

**Comment by nitrocode** [comment]
@lgallard you'll have to run `make init && make readme` to regenerate the readme locally and then push up since the bot doesnt have access to the fork.

**Comment by Nuru** [comment]
@lgallard wrote
> 
> We checked [from our] side but we are not clear about what permission is needed by cloudpossebot in our repo. In fact the forked repo is public https://github.com/binbashar/terraform-aws-firewall-manager
> 

See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork for details about allowing us to modify your PR.

**Comment by lgallard** [comment]
@Nuru @nitrocode conflicts were fixed. On the other hand I cound't find the option you pointed it out in here https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork 

Please let us know if we need to do anything else to close the PR 🙏🏻

**Comment by nitrocode** [comment]
@lgallard according to github, there are still conflicts. Could you look it over again ?

**Comment by Nuru** [comment]
@lgallard Sorry about the difficulty getting this PR formatted and merged. Because we cannot push to your branch, we and our automated tools are not able to fix these issues for you.

You need to resolve the conflicts as explained by GitHub, and again run
```
make init
make pr/auto-format
```
and then commit and push the result. 

Note: any conflicts in `README.md` or `docs/terraform.md` can be safely ignored by running
```
git add README.md docs/terraform.md
```
before running `git commit` and then running the `make` commands.

**Comment by Nuru** [comment]
@lgallard So that you do not have to do any more work, I am copying your changes to PR #17 and committing them there. I hope you don't mind, and if you do, please let me know what you would like me to do about it.

**Comment by lgallard** [comment]
@Nuru thank you! That works for us. I hope next PRs we can find the permission issue on our end.

**Pull request closed without merging**
